export default {
  START_AS_A_TRADERS: 'ابدأ كمتداول',
  LANGUAGE_PAGE_P1: '',
  LANGUAGE_PAGE_P2: '',
  LANGUAGE_PAGE_P3: '',
  ENGLISH: 'إنجليزي',
  ARABIC: 'عربي',
  OR: 'أو',
  SEARCH: 'بحث',
  LOGIN: 'تسجيل الدخول',
  SIGNNOW: 'سجل الان',
  SIGN_IN_AS_A_TRADERS: 'تسجيل الدخول كمتداولين',
  ENTER_YOUR_EMAIL: 'أدخل بريدك الإلكتروني',
  ENTER_YOUR_TOKEN: 'أدخل الرمز الخاص بك',
  PASSWORD: 'كلمة المرور',
  FORGOT_PASSWORD: 'هل نسيت كلمة السر؟',
  DONT_HAVE_ACCOUNT_SIGNIN: 'ليس لديك حساب؟',
  GET_STARTED: 'البدء',
  LOADING: 'جار التحميل...',
  FORGET_YOUR_PASSWORD: 'نسيت رقمك السري؟',
  SUBMIT: 'إرسال',
  GOOGLE: 'غوغل',
  FACEBOOK: 'فيسْبوكيّ',
  TRADER_BTN: 'تاجر',
  SIGNUP: 'اشتراك',
  ENTER_NAME: 'أدخل الاسم',
  BUSINESS_NAME: 'الاسم التجاري',
  ENTER_EMAIL_ID: 'أدخل معرف البريد الإلكتروني',
  MOBILE_NUMBER: 'رقم الهاتف المحمول',
  CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
  MESSAGE: 'رسالة',
  TERMS_AND_CONDITIONS: 'البنود و الظروف',
  ALREADY_HAVE_ACCOUNT_LOGIN: 'لديك حساب بالفعل؟ تسجيل الدخول',
  TOTAL: 'المجموع',
  SEARCH_BY: 'البحث عن طريق',
  PRODUCT_ARE_AVALIABLE: 'المنتج متاح',
  HI: 'أهلا',
  HOME: 'الصفحة الرئيسية',
  PROFILE: 'حساب تعريفي',
  CHANGE_PASSWORD: 'تغيير كلمة المرور',
  LOGOUT: 'تسجيل خروج',
  UPDATE: 'تحديث',
  ADD_PRODUCT: 'أضف المنتجات',
  ADD_CONFIGURABLE_PRODUCT: 'إضافة منتج شكلي',
  TO_DO_LIST: 'عمل قائمة',
  ACCOUNT: 'حساب',
  ORDER_LIST: 'لائحة الطلبات',
  ORDER_DETAILS: 'تفاصيل الطلب',
  PRODUCT_CATEGORY: 'فئة المنتج',
  PRODUCT_SUB_CATEGORY: 'فئة المنتج الفرعية',
  PRODUCT_TITLE: 'عنوان المنتج',
  DESCRIPTIOn: 'وصف',
  PRICE: 'السعر',
  QUANTITY: 'كمية',
  MAX_ORDER: 'ماكس النظام',
  COLOR: 'اللون',
  SIZE: 'بحجم',
  XL: 'XL',
  L: 'Lإل',
  M: 'م',
  S: 'س',
  XS: 'XS',
  CAP_ADD_PRODUCT: 'أضف منتج',
  RESET_PASSWORD: 'إعادة تعيين كلمة المرور',
  UPLOAD_REQUIRED_FILE: 'تحميل الملف المطلوب',
  EDIT_PROFILE: 'تعديل الملف الشخصي',
  ADDRESS: 'تبوك',
  UPLOAD_DOCUMENTS: 'تحميل المستندات',
  TRADE_LICENCE: 'رخصة تجارية',
  PAN_CARD: 'بطاقة الطعام',
  IDENTITY_PROOF: 'إثبات الهوية',
  CANCEL: 'إلغاء',
  PAYMENT_DETAILS: 'قائمة المنتجات الخاصة بي',
  PRODUCT_LIST: 'قائمة المنتجات',
  MY_PAYMENT_DETAILS: 'تفاصيل الدفع الخاصة بي',
  ARE_YOU_SURE_YOU_WANT_TO_Delete:'هل انت متأكد انك تريد حذف حسابك',
  Delete_Account:'حذف الحساب',
  SIGN_OUT: 'خروج',
  NOTIFICATION: 'تنبيه',
  REVIEWS: 'المراجعات',
  VENDOR_DETAILS: 'تفاصيل البائع',
  All_Products: 'جميع المنتجات',
  Active_Products: 'المنتجات النشطة',
  Inactive_Products: 'المنتجات غير النشطة',
  NAME: 'اسم',
  NO_PRODUCTS: 'لا توجد منتجات',
  TYPE_MORE_THAN_2_CHARACTERS: 'اكتب أكثر من حرفين للبحث التلقائي',
  SEARCH_Screen: 'شاشة البحث',
  EDIT_PRODUCT: 'تحرير المنتج',
  DOCUMENTS_UPLOADED_WAITING_FOR_APPROVAL:
    'المستندات التي تم تحميلها في انتظار الموافقة من المسؤول.',
  DOCUMENTS_APPROVED_YOU_CAN_CREATE_PRODUCTS_NOW:
    'تمت الموافقة على المستندات ، يمكنك إنشاء منتجات الآن.',
  OLD_PASSWORD: 'كلمة المرور القديمة',
  New_Password: 'كلمة السر الجديدة',
  CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
  ALL_ORDERS: 'جميع الطلبات',
  UPCOMING_ORDERS: 'الطلبات القادمة',
  PAST_ORDERS: 'الطلبات السابقة',
  ORDERS_AVAILABLE: 'الطلبات المتاحة',
  PRODUCT_TITLE: 'عنوان المنتج',
  DESCRIPTION: 'وصف',
  Price: 'سعر',
  Special_Price: 'سعر خاص',
  QUANTITY: 'كمية',
  MAX_ORDER: 'الحد الأقصى للطلب',
  TOTAL_TRANSACTION: 'إجمالي المعاملات',
  OVERALL: 'شاملة',
  DUE_AMOUNT: 'مبلغ مستحق',
  Receive_Amount: 'استلام المبلغ',
  Total_Customer: 'إجمالي العميل',
  Customer_This_Month: 'العميل هذا الشهر',
  Customer_Last_Month: 'العميل الشهر الماضي',
  Recent_Received: 'وردت مؤخرا',
  ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  OK: 'موافق',
  EDIT_DESCRIPTION: 'تحرير الوصف',
  NOTE_EDIT_PRODUCT_FROM_HOME:
    'ملاحظة: يمكنك فقط تحرير منتجاتك من قسم المنتج الخاص بي.',
  NOTE_NOTE_EDIT_PRODUCT_CONFIGURABLE:
    'ملاحظة: المنتج القابل للتكوين غير قابل للتحرير.',
  ARE_YOU_SURE_YOU_WANT_TO_EXIT: 'هل أنت متأكد أنك تريد الخروج؟',
  YES: 'نعم',
  PLEASE_ENTER_A_VALID_PRICE: 'الرجاء إدخال رقم سعر صالح',
  PLEASE_ENTER_A_VALID_SPECIAL_PRICE: 'الرجاء إدخال رقم سعر خاص صالح',
  PLEASE_ENTER_A_VALID_QUANTITY: 'الرجاء إدخال رقم كمية صحيح',
  PLEASE_ENTER_A_VALID_MAX_ORDER: 'الرجاء إدخال أقصى رقم صالح للطلب',
};
