export default {
  START_AS_A_TRADERS: 'Start as a Traders',
  LANGUAGE_PAGE_P1: '',
  LANGUAGE_PAGE_P2: '',
  LANGUAGE_PAGE_P3: '',
  ENGLISH: 'ENGLISH',
  ARABIC: 'ARABIC',
  OR: 'OR',
  SEARCH: 'Search',
  SIGNNOW: 'Sign Now',
  LOGIN: 'LOGIN',
  SIGN_IN_AS_A_TRADERS: 'Sign In as a Traders',
  ENTER_YOUR_EMAIL: 'Enter your email',
  ENTER_YOUR_TOKEN: 'Enter your token',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  DONT_HAVE_ACCOUNT_SIGNIN: "Don't have account ?Sign Up",
  GET_STARTED: 'Get Started',
  LOADING: 'Loading...',
  FORGET_YOUR_PASSWORD: 'Forgot Your Password?',
  SUBMIT: 'Submit',
  GOOGLE: 'Google',
  FACEBOOK: 'Facebook',
  TRADER_BTN: 'TRADER',
  SIGNUP: 'SIGN UP',
  ENTER_NAME: 'Enter Name',
  BUSINESS_NAME: 'Business Name',
  ENTER_EMAIL_ID: 'Enter Email Id',
  MOBILE_NUMBER: 'Mobile Number',
  CONFIRM_PASSWORD: 'Confirm Password',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  ALREADY_HAVE_ACCOUNT_LOGIN: 'Already have account?Login',
  TOTAL: 'Total',
  SEARCH_BY: 'Search by',
  PRODUCT_ARE_AVALIABLE: 'product are available',
  HI: 'Hi',
  HOME: 'Home',
  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  MESSAGE: 'Message',
  LOGOUT: 'Logout',
  UPDATE: 'UPDATE',
  ADD_PRODUCT: 'Add Products',
  ADD_CONFIGURABLE_PRODUCT: 'Add configurable Product',
  TO_DO_LIST: 'To Do List',
  ACCOUNT: 'Account',
  ORDER_LIST: 'Order List',
  ORDER_DETAILS: 'Order Details',
  PRODUCT_CATEGORY: 'Product Category',
  PRODUCT_SUB_CATEGORY: 'Product Sub Category',
  PRODUCT_TITLE: 'Product Tttle',
  DESCRIPTIOn: 'Description',
  PRICE: 'Price',
  QUANTITY: 'Quantity',
  MAX_ORDER: 'MAX Order',
  COLOR: 'Color',
  SIZE: 'Size',
  XL: 'XL',
  L: 'L',
  M: 'M',
  S: 'S',
  XS: 'XS',
  CAP_ADD_PRODUCT: 'ADD PRODUCT',
  RESET_PASSWORD: 'Reset Password',
  UPLOAD_REQUIRED_FILE: 'Upload required file',
  EDIT_PROFILE: 'Edit Profile',
  ADDRESS: 'Address',
  UPLOAD_DOCUMENTS: 'Upload Documents',
  TRADE_LICENCE: 'Trade Licence',
  PAN_CARD: 'Pan Card',
  IDENTITY_PROOF: 'Identity Proof',
  CANCEL: 'Cancel',
  PAYMENT_DETAILS: 'Payment Details',
  PRODUCT_LIST: 'My Product List',
  MY_PAYMENT_DETAILS: 'My Payment Details',
  Delete_Account:'Delete Account',
  SIGN_OUT: 'Sign Out',
  NOTIFICATION: 'Notification',
  REVIEWS: 'Reviews',
  VENDOR_DETAILS: 'Vendor details',
  All_Products: 'All Products',
  Active_Products: 'Active Products',
  Inactive_Products: 'Inactive Products',
  NAME: 'Name',
  NO_PRODUCTS: 'No Products',
  TYPE_MORE_THAN_2_CHARACTERS: 'Type more than 2 characters for auto search',
  SEARCH_Screen: 'Search Screen',
  EDIT_PRODUCT: 'Edit Product',
  DOCUMENTS_UPLOADED_WAITING_FOR_APPROVAL:
    'Documents uploaded waiting for approval from admin.',
  DOCUMENTS_APPROVED_YOU_CAN_CREATE_PRODUCTS_NOW:
    'Documents approved you can create products now.',
  OLD_PASSWORD: 'Old Password',
  New_Password: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  ALL_ORDERS: 'All Orders',
  UPCOMING_ORDERS: 'Upcoming Orders',
  PAST_ORDERS: 'Past Orders',
  ORDERS_AVAILABLE: 'Orders Available',
  PRODUCT_TITLE: 'Product Title',
  DESCRIPTION: 'Description',
  Price: 'Price',
  Special_Price: 'Special price',
  QUANTITY: 'Quantity',
  MAX_ORDER: 'Max Order',
  TOTAL_TRANSACTION: 'Total transactions',
  OVERALL: 'Overall',
  DUE_AMOUNT: 'Due Amount',
  Receive_Amount: 'Receive Amount',
  Total_Customer: 'Total Customer',
  Customer_This_Month: 'Customer This Month',
  Customer_Last_Month: 'Customer Last Month',
  Recent_Received: 'Recent Received',
  ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'Are you sure you want to Sign Out?',
  ARE_YOU_SURE_YOU_WANT_TO_Delete:'Are you sure you want to Delete Your Account?',
  OK: 'OK',
  EDIT_DESCRIPTION: 'Edit Description',
  NOTE_EDIT_PRODUCT_FROM_HOME:
    'Note: You can only edit your products from my product section.',
  NOTE_NOTE_EDIT_PRODUCT_CONFIGURABLE:
    'Note: Configurable product is not editable.',
  ARE_YOU_SURE_YOU_WANT_TO_EXIT: 'Are you sure you want to exit?',
  YES: 'YES',
  PLEASE_ENTER_A_VALID_PRICE: 'Please Enter a valid price number',
  PLEASE_ENTER_A_VALID_SPECIAL_PRICE:
    'Please Enter a valid special price number',
  PLEASE_ENTER_A_VALID_QUANTITY: 'Please Enter a valid quantity number',
  PLEASE_ENTER_A_VALID_MAX_ORDER: 'Please Enter a valid Max order number',
};
