// User Login
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
// User Logout
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';
// User Signup
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
// OTP Verify
export const OTP_VERIFY = 'OTP_VERIFY';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILED = 'OTP_VERIFY_FAILED';
// Resend OTP
export const RESEND_OTP = 'RESEND_OTP';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILED = 'RESEND_OTP_FAILED';
// Forgot password
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
// Category list
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAILED = 'CATEGORY_LIST_FAILED';
// Sub category list
export const SUB_CATEGORY_LIST = 'SUB_CATEGORY_LIST';
export const SUB_CATEGORY_LIST_SUCCESS = 'SUB_CATEGORY_LIST_SUCCESS';
export const SUB_CATEGORY_LIST_FAILED = 'SUB_CATEGORY_LIST_FAILED';
// Recent job list
export const RECENT_JOB = 'RECENT_JOB';
export const RECENT_JOB_SUCCESS = 'RECENT_JOB_SUCCESS';
export const RECENT_JOB_FAILED = 'RECENT_JOB_FAILED';
// Get User Profile
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
// Update User Profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
// Change Password
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const CLEAR_UPDATE_MESSAGE = 'CLEAR_UPDATE_MESSAGE';

// Get Expertise
export const GET_EXPERTISE = 'GET_EXPERTISE';
export const GET_EXPERTISE_SUCCESS = 'GET_EXPERTISE_SUCCESS';
export const GET_EXPERTISE_FAILED = 'GET_EXPERTISE_FAILED';

//create job
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILED = 'CREATE_JOB_FAILED';

export const APPLY_JOB = 'APPLY_JOB';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED';

export const CLEAR_JOB_MESSAGE = 'CLEAR_JOB_MESSAGE';
export const APPLY_JOB_MESSAGE = 'APPLY_JOB_MESSAGE';

export const APPLIED_JOB = 'APPLIED_JOB';
export const APPLIED_JOB_SUCCESS = 'APPLIED_JOB_SUCCESS';
export const APPLIED_JOB_FAILED = 'APPLIED_JOB_FAILED';

export const OFFERED_JOB = 'OFFERED_JOB';
export const OFFERED_JOB_SUCCESS = 'OFFERED_JOB_SUCCESS';
export const OFFERED_JOB_FAILED = 'OFFERED_JOB_FAILED';

export const APPROVED_JOB = 'APPROVED_JOB';
export const APPROVED_JOB_SUCCESS = 'APPROVED_JOB_SUCCESS';
export const APPROVED_JOB_FAILED = 'APPROVED_JOB_FAILED';

export const ACCEPTED_JOB = 'ACCEPTED_JOB';
export const ACCEPTED_JOB_SUCCESS = 'ACCEPTED_JOB_SUCCESS';
export const ACCEPTED_JOB_FAILED = 'ACCEPTED_JOB_FAILED';

export const RECEIVED_JOB = 'RECEIVED_JOB';
export const RECEIVED_JOB_SUCCESS = 'RECEIVED_JOB_SUCCESS';
export const RECEIVED_JOB_FAILED = 'RECEIVED_JOB_FAILED';


export const DENIED_JOB = 'DENIED_JOB';
export const DENIED_JOB_SUCCESS = 'DENIED_JOB_SUCCESS';
export const DENIED_JOB_FAILED = 'DENIED_JOB_FAILED';


export const APPROVE_JOB = 'APPROVE_JOB';
export const APPROVE_JOB_SUCCESS = 'APPROVE_JOB_SUCCESS';
export const APPROVE_JOB_FAILED = 'APPROVE_JOB_FAILED';
export const APPROVE_JOB_MESSAGE = 'APPROVE_JOB_MESSAGE';


export const ACCEPTAPPROVE_JOB = 'ACCEPTAPPROVE_JOB';
export const ACCEPTAPPROVE_JOB_SUCCESS = 'ACCEPTAPPROVE_JOB_SUCCESS';
export const ACCEPTAPPROVE_JOB_FAILED = 'ACCEPTAPPROVE_JOB_FAILED';
export const ACCEPTAPPROVE_JOB_MESSAGE = 'ACCEPTAPPROVE_JOB_MESSAGE';

export const START_JOB = 'START_JOB';
export const START_JOB_SUCCESS = 'START_JOB_SUCCESS';
export const START_JOB_FAILED ='START_JOB_FAILED';
export const START_JOB_MESSAGE = 'START_JOB_MESSAGE';

//get all job
export const GET_ALL_JOB = 'GET_JOB';
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS';
export const GET_ALL_JOB_FAILED = 'GET_ALL_JOB_FAILED';

//get job details
export const GET_JOB_DETAILS = 'GET_JOB_DETAILS';
export const GET_JOB_DETAILS_SUCCESS = 'GET_JOB_DETAILS_SUCCESS';
export const GET_JOB_DETAILS_FAILED = 'GET_JOB_DETAILS_FAILED';

export const GET_JOB_SEARCH = 'GET_JOB_SEARCH';
export const GET_JOB_SEARCH_SUCCESS = 'GET_JOB_SEARCH_SUCCESS';
export const GET_JOB_SEARCH_FAILED = 'GET_JOB_SEARCH_FAILED';

//get all users
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const NOTIFICATION_READ = 'NOTIFICATION_READ'
export const NOTIFICATION_READ_SUCCESS = 'NOTIFICATION_READ_SUCCESS'
export const NOTIFICATION_READ_FAILED = 'NOTIFICATION_READ_FAILED'

export const NOTIFICATION_LIST = 'NOTIFICATION_LIST'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAILED = 'NOTIFICATION_LIST_FAILED'

export const GET_FRIENDLIST = 'GET_FRIENDLIST'
export const GET_FRIENDLIST_SUCCESS = 'GET_FRIENDLIST_SUCCESS'
export const GET_FRIENDLIST_FAILED = 'GET_FRIENDLIST_FAILED'

export const INVITE_FRIEND = 'INVITE_FRIEND'
export const INVITE_FRIEND_SUCCESS = 'INVITE_FRIEND_SUCCESS'
export const INVITE_FRIEND_FAILED = 'INVITE_FRIEND_FAILED'

export const REQUEST_FRIEND = 'REQUEST_FRIEND'
export const REQUEST_FRIEND_SUCCESS = 'REQUEST_FRIEND_SUCCESS'
export const REQUEST_FRIEND_FAILED = 'REQUEST_FRIEND_FAILED'

export const ACCEPT_FRIEND = 'ACCEPT_FRIEND'
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS'
export const ACCEPT_FRIEND_FAILED = 'ACCEPT_FRIEND_FAILED'

export const REJECT_FRIEND = 'REJECT_FRIEND'
export const REJECT_FRIEND_SUCCESS = 'REJECT_FRIEND_SUCCESS'
export const REJECT_FRIEND_FAILED = 'REJECT_FRIEND_FAILED'

export const CLEAR_REJECT_MESSAGE = 'CLEAR_REJECT_MESSAGE';

export const GET_CHATHISTORY = 'GET_CHATHISTORY'
export const GET_CHATHISTORY_SUCCESS = 'GET_CHATHISTORY_SUCCESS'
export const GET_CHATHISTORY_FAILED = 'GET_CHATHISTORY_FAILED'

export const GET_CHAT= 'GET_CHAT'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAILED = 'GET_CHAT_FAILED'

export const CREATE_CHAT = 'CREATE_CHAT'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_FAILED = 'CREATE_CHAT_FAILED'


export const LOCATION_CHANGE ='LOCATION_CHANGE'


export const CARD_DETAILS = 'CARD_DETAILS'
export const CARD_DETAILS_SUCCESS = 'CARD_DETAILS_SUCCESS'
export const CARD_DETAILS_FAILED ='CARD_DETAILS_FAILED'

export const SAVE_BANK_DETAILS = 'SAVE_BANK_DETAILS'
export const SAVE_BANK_DETAILS_SUCCESS = 'SAVE_BANK_DETAILS_SUCCESS'
export const SAVE_BANK_DETAILS_FAILED = 'SAVE_BANK_DETAILS_FAILED'

export const BANK_DETAILS = 'BANK_DETAILS'
export const BANK_DETAILS_SUCCESS = 'BANK_DETAILS_SUCCESS'
export const BANK_DETAILS_FAILED = 'BANK_DETAILS_FAILED'


export const JOB_WORKED = 'JOB_WORKED'
export const JOB_WORKED_SUCCESS = 'JOB_WORKED_SUCCESS'
export const JOB_WORKED_FAILED = 'JOB_WORKED_FAILED'
export const POSITION_CHANGE = 'POSITION_CHANGE'



export const JOB_CREATED = 'JOB_CREATED'
export const JOB_CREATED_SUCCESS = 'JOB_CREATED_SUCCESS'
export const JOB_CREATED_FAILED = 'JOB_CREATED_FAILED'
