export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_FAVORITE_TRAINING = 'SET_FAVORITE_TRAINING';
export const SET_CART_ITEM = 'SET_CART_ITEM';
export const SET_CART_ITEM_LIST = 'SET_CART_ITEM_LIST';
