import {StyleSheet} from 'react-native';
import {COLORS, FONT_FAMILY} from '../../utils/Const';
import {hp, wp} from '../../utils/ResponsiveLayout';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  topContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(12),
    marginHorizontal: wp(18),
  },
  topIcon: {
    width: wp(24),
    height: wp(24),
    resizeMode: 'contain',
  },
  locationTitle: {
    fontSize: wp(14),
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.LATO_BOLD,
  },
  addressText: {
    fontSize: wp(12),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.NICKEL,
  },
  searchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(34),
    marginHorizontal: wp(18),
    marginBottom: hp(12),
  },
  filterContainer: {
    paddingHorizontal: wp(20),

    backgroundColor: COLORS.WHITE,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flex: 1,
    // height: hp(55),
  },
  filterIcon: {
    // height: wp(24),
    width: wp(24),
    resizeMode: 'contain',
  },
  categoryContainer: {
    height: hp(80),
    width: wp(80),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
  },
  categoryIcon: {
    height: wp(40),
    width: wp(40),
    resizeMode: 'contain',
  },
  categoryTitle: {
    marginTop: hp(6),
    fontSize: wp(14),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.NICKEL,
    textAlign: 'center',
    // width: '90%',
    flexWrap: 'wrap',
  },
  jobContainer: {
    marginTop: hp(4),
    marginHorizontal: wp(18),
  },
  recentJobTitle: {
    fontSize: wp(20),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    fontWeight: '600',
    color: COLORS.DARK_CHARCOAL,
    marginBottom: hp(20),
  },
  jobItemContainer: {
    marginBottom: hp(24),
    paddingBottom: hp(20),
    marginEnd: hp(30),
    width: '46%',
    borderRadius: 12,
    backgroundColor: COLORS.WHITE,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    
  },
  jobImg: {
    width: '100%',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    height: hp(200),
  },
  priceContainer: {
    height: wp(45),
    width: wp(45),
    backgroundColor: COLORS.YELLOW_GREEN,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    position: 'absolute',
    top: hp(-40),
    right: wp(10),
  },
  priceText: {
    fontSize: wp(12),
    fontFamily: FONT_FAMILY.LATO_BOLD,
    color: COLORS.WHITE,
  },
  dateText: {
    fontSize: wp(10),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.BLACK,
    marginTop: hp(10),
    marginLeft: wp(10),
  },
  titleText: {
    fontSize: wp(16),
    marginHorizontal: wp(10),
    fontFamily: FONT_FAMILY.LATO_BOLD,
    color: COLORS.DARK_CHARCOAL,
    marginTop: hp(2),
  },
  descText: {
    fontSize: wp(14),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.NICKEL,
    marginHorizontal: wp(10),
    marginVertical: hp(12)
  },
  buttonContainer: {
    flexDirection: 'row',
    // justifyContent: 'flex-end',
    alignItems: 'center',
    marginHorizontal: wp(5),
    marginTop: hp(22),
    
   
  },
  buttonStyle: {
    paddingVertical: hp(5),
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.YELLOW_GREEN,
  },
  buttonText: {
    fontSize: wp(12),
    fontFamily: FONT_FAMILY.LATO_BOLD,
    color: COLORS.YELLOW_GREEN,
  },
  middleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: wp(10),
    width: '100%',
  },
  userText: {
    fontSize: wp(12),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.DARK_CHARCOAL,
    marginLeft: wp(4),
  },

  searchText:{
    fontSize: wp(20),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.DARK_CHARCOAL,
    marginLeft: wp(10),
  },

  viewText: {
    fontSize: wp(12),
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    color: COLORS.DARK_CHARCOAL,
  },
  centeredView: {
    flex: 0.92,
    justifyContent: 'space-between',
    backgroundColor: COLORS.WHITE,
    width: '100%',
  },
  centeredView2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  textInputViewCss: {
    borderWidth: 1,
    borderColor: COLORS.DARKGREYY,
    borderRadius: 10,
  },
  textcomCSS: {
    fontSize: wp(14),
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.LATO_BOLD,
    marginTop: hp(4),
  },
  pickertextclass: {
    fontSize: wp(14),
    color: COLORS.NICKEL,
  },

  meninputviewCSS: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputtextCSS: {
    height: hp(50),
    width: '100%',
    fontSize: wp(14),
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    borderColor: COLORS.NICKEL,
    borderRadius: 12,
    paddingHorizontal: wp(12),
    marginTop: hp(18),
  },
  distancecss: {
    fontSize: wp(14),
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.LATO_BOLD,
    marginTop: hp(16),
  },
  expertiseContainer: {
    justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
    maxHeight: hp(300),
  },
  expertiseImg: {
    height: hp(160),
    width: wp(160),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    resizeMode: 'contain',
  },
  expertiseName: {
    fontFamily: FONT_FAMILY.LATO_BOLD,
    fontSize: wp(14),
    color: COLORS.BLACK,
    textAlign: 'left',
    marginLeft: 8,
    marginTop: hp(12),
  },
  expertiseType: {
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    fontSize: wp(12),
    color: COLORS.BLACK,
    textAlign: 'left',
    marginLeft: 8,
    marginTop: hp(6),
    width: wp(150),
  },
  expertisePriceContainer: {
    backgroundColor: COLORS.YELLOW_GREEN,
    borderRadius: 6,
    padding: 6,
    position: 'absolute',
    bottom: -10,
    right: 10,
    zIndex: 1,
  },
  expertisePriceText: {
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.LATO_REGULAR,
    fontSize: wp(10),
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    // alignItems: "center",
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    flex: 1,
    width: '90%',
  },
});
