export default {
  START_AS_A_TRADERS: 'ابدأ كمنصة المتداولين',
  START_DESC: 'الحياة البيئية في الغد مجانية في العقارات. إنها ليست بوابة أو شاحنة نقية.',
  LANGUAGE_PAGE_P1: '',
  LANGUAGE_PAGE_P2: '',
  LANGUAGE_PAGE_P3: '',
  ENGLISH: 'إنجليزي',
  ARABIC: 'عربي',
  OR: 'أو',
  SEARCH: "بحث",
  LOGIN: "تسجيل الدخول",
  SIGNNOW: "سجل الان",
  SIGN_IN_AS_A_TRADERS: "تسجيل الدخول كمتداولين",
  ENTER_YOUR_EMAIL: "أدخل بريدك الإلكتروني",
  ENTER_YOUR_PHONE_NUMBER: "أدخل رقم هاتفك",
  EMAIL: "البريد الإلكتروني",
  Mobile_Number:"رقم الهاتف المحمول",
  Old_MOBILE_NUMBER:"رقم الجوال القديم",
  New_MOBILE_NUMBER:'رقم جوال جديد',
  PASSWORD: "كلمة المرور",
  NEWPASSWORD:'كلمة المرور الجديدة',
  FORGOT_PASSWORD: "هل نسيت كلمة السر؟",
  DONT_HAVE_ACCOUNT_SIGNIN: "ليس لديك حساب؟",
  GET_STARTED: "البدء",
  LOADING: 'جار التحميل...',
  FORGET_YOUR_PASSWORD: 'نسيت رقمك السري؟',
  LOGIN_WITH_MOBILE_NUMBER:'تسجيل الدخول باستخدام رقم الهاتف المحمول',
  ENTER_YOUR_ONE_TIME_OTP:'أدخل رقمك السري لمرة واحدة',
  SUBMIT: 'إرسال',
  SEND_OTP:'إرسال',
  SEND_EMAIL:'ارسل بريد الكتروني',
  Mobile_Number_Update:'تحديث رقم الجوال',
  Get_Otp:'احصل على',
  ENTER_OTP:'أدخل OTP',
  VERIFY:'يؤكد',
  GOOGLE: 'غوغل',
  FACEBOOK: 'فيسبوك',
  TRADER_BTN: 'تاجر',
  SIGNUP: 'اشتراك',
  ENTER_NAME: 'أدخل الاسم',
  BUSINESS_NAME: 'الاسم التجاري',
  ENTER_EMAIL_ID: "أدخل معرف البريد الإلكتروني",
  MOBILE_NUMBER: 'رقم الهاتف المحمول',
  CONFIRM_PASSWORD: "تأكيد كلمة المرور",
  MESSAGE: 'رسالة',
  TERMS_AND_CONDITIONS: "البنود و الظروف",
  ALREADY_HAVE_ACCOUNT_LOGIN: 'لديك حساب بالفعل؟',
  TOTAL: 'المجموع',
  PRODUCT_ARE_AVALIABLE: 'المنتج متاح',
  HI: 'أهلا',
  HOME: 'الصفحة الرئيسية',
  PROFILE: 'حساب تعريفي',
  CHANGE_PASSWORD: 'تغيير كلمة المرور',
  LOGOUT: 'تسجيل خروج',
  UPDATE: 'تحديث',
  ADD_PRODUCT: 'أضف المنتجات',
  TO_DO_LIST: 'عمل قائمة',
  ACCOUNT: 'حساب',
  PRODUCT_CATEGORY: 'فئة المنتج',
  PRODUCT_SUB_CATEGORY: 'فئة المنتج الفرعية',
  PRODUCT_TITLE: "عنوان المنتج",
  DESCRIPTIOn: 'وصف',
  PRICE: 'السعر',
  QUANTITY: 'جودة',
  MAX_ORDER: 'ماكس النظام',
  COLOR: 'اللون',
  SIZE: 'بحجم',
  XL: 'XL',
  L: 'Lإل',
  M: 'م',
  S: 'س',
  XS: 'XS',
  CAP_ADD_PRODUCT: 'أضف منتج',
  SIGN_IN: 'تسجيل الدخول',
  EMAIL_ERR: 'يرجى إدخال عنوان البريد الإلكتروني.',
  LOGIN_1: 'تسجيل الدخول',
  CANCEL: 'إلغاء',
  OK: 'نعم',
  VALID_EMAIL: 'رجاء قم بإدخال بريد الكتروني صحيح.',
  ENTER_CONPASS:"أدخل كلمة المرور تأكيد",
  ENTER_PASS: 'الرجاء إدخال كلمة المرور.',
  ENTER_NEWPASS: 'الرجاء إدخال كلمة المرور.',
  PASS_ERR: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل ، وحرف واحد كبير ، وحرف صغير واحد ، وتحتوي على رقم واحد على الأقل.',
  LOGIN_SUCCESS: 'تم تسجيل الدخول بنجاح',
  LOGIN_SUCCESS2: 'تسجيل دخولك ناجح',
  LOGIN_FAIL: 'فشل عملية الدخول',
  LOGIN_FAIL2: 'الرجاء معاودة المحاولة في وقت لاحق.',
  TREND_COLL: 'مجموعة رائجة',
  MYORDER: 'طلبي',
  MYCART: 'عربتي',
  LOGOUT_FROM_APP:'تسجيل خروج',
  MYWISH: 'قائمة امنياتي',
  ALLTRAD: 'التجار',
  PRODUCTS: 'منتجات',
  CUSTOMERSERV: 'خدمة الزبائن',
  FAQ: 'التعليمات',
  PRIVACYPOL: 'سياسة الخصوصية',
  ABOUTUS: 'معلومات عنا',
  Delete_Account:'حذف الحساب',
  Delete_Your_Account:'حذف الحساب',
  AED: 'درهم إماراتي',
  REVIEWS: 'المراجعات',
  REVIEW: 'إعادة النظر',
  REVIEW2: 'إعادة النظر *',
  ADDTOCART: 'أضف إلى السلة',
  SUBMITREVIEW: 'إرسال المراجعة',
  ADDEDCART: 'تمت الإضافة إلى عربة التسوق',
  CARTTOTAL: 'إجمالي سلة التسوق',
  CONTISHOPPING: 'مواصلة التسوق',
  CHECKOUT: 'الدفع',
  PRODETAILS: 'تفاصيل المنتج',
  YOUAREREVIEWING: 'أنت تراجع:',
  YOURRATING: 'تقييمك *',
  VALUE: 'قيمة',
  NICKNAME: 'كنية *',
  SUMMARY: 'ملخص *',
  SELECT_SUITABLE_SC: 'يرجى تحديد الحجم واللون المناسبين',
  REVIEW_SUBMIT: 'تم إرسال المراجعة',
  REVIEW_SUBMIT_FAILED: 'مراجعة إرسال فشل',
  Are_you_sure_you_want_to_Exit: 'هل تريد الخروج من التطبيق؟',
  CHANGE_PASS_FAIL: 'فشل تغيير كلمة المرور',
  CHANGE_PASS_SUCCESS: 'تم تغيير كلمة المرور الخاصة بك بنجاح.',
  REGISTRATION: 'التسجيل',
  ENTER_THE_NAME: 'الرجاء إدخال الاسم',
  ENTER_PHONE_NO: 'الرجاء إدخال رقم الهاتف.',
  ENTER_10DIGIT_NO: 'الرجاء إدخال رقم الهاتف المتحرك الإماراتي الصحيح.',
  PASS_NOT_MATCH: 'تأكيد كلمة المرور لا يتطابق مع كلمة المرور.',
  ACCEPT_TC: 'الرجاء قبول الشروط والأحكام الخاصة بنا.',
  REG_SUCCESS: 'تم التسجيل بنجاح',
  REG_SUCCESS2: 'تم تسجيلك بنجاح.',
  REG_ERR: 'فشل التسجيل د',
  PROFILE_UPDATED_SUCCESS: 'تم تحديث الملف الشخصي بنجاح.',
  SOMETHING_WENT_WRONG: 'هناك خطأ ما. حاول مرة اخرى.',
  NAME: 'اسم',
  DATE_OF_BIRTH: 'تاريخ الولادة',
  DATE_OF_META: 'تاريخ تكرار الفوقية',
  DELETE_SUCCESS: 'تم الحذف بنجاح',
  CART: 'عربة التسوق',
  PROCEED_TO_BUY: 'على وشك الشراء',
  VIEW_AND_EDIT_CART:'عرض وتحرير عربة التسوق',
  ITEMS: 'العناصر',
  ITEMS2: 'العناصر',
  CART_EMPTY: 'سلة التسوق الخاصة بك تبدو فارغة!',
  START_SHOPPING: 'ابدأ التسوق عبر الإنترنت',
  QUANTITY2: 'كمية',
  DELETE: 'حذف',
  SUBTOTAL: 'المجموع الفرعي',
  FILL_ALL_FIELDS: 'لو سمحت أملأ كل الحقول',
  ADDRESS: 'Address',
  ADDRESS_ADD_SUCCESS: 'تمت إضافة عنوان الشحن بنجاح.',
  ADDRESS_ADD_FAIL: 'فشل العنوان',
  PINCODE_NOT_AVAILABLE: 'هذا الرمز السري غير متوفر',
  SHIPPING_ADD: 'عنوان الشحن',
  NO_ADD: 'لم يتم العثور على عنوان.',
  DELIVERY_TO_ADD: 'التسليم لهذا العنوان',
  EDIT_ADD: 'تعديل العنوان',
  ADD_NEW_ADD: 'أضف عنوان جديد',
  FIRST_NAME: 'الاسم الاول',
  LAST_NAME: 'الكنية',
  HOUSE_NO: 'رقم الدار',
  STREET_NO: 'رقم الشارع',
  CITY: 'مدينة',
  ZIPCODE: 'الرمز البريدي',
  STATE: 'حالة',
  COUNTRY: 'بلد',
  TELEPHONE: 'هاتف',
  DEFAULT_SHIP_ADD: 'تعيين عنوان الشحن الافتراضي',
  DEFAULT_BILL_ADD: 'تعيين عنوان الفواتير الافتراضي',
  ENTER_CARD_NO: 'الرجاء إدخال الرقم على البطاقة',
  ENTER_CARD_NAME: 'الرجاء إدخال الاسم على البطاقة',
  ENTER_EXPIRY_DATE: 'الرجاء إدخال تاريخ انتهاء الصلاحية',
  ENTER_CVV: 'الرجاء إدخال السيرة الذاتية',
  PRICE_DET: 'تفاصيل السعر',
  DELIVERY_CHARGES: 'رسوم التوصيل',
  TAX: 'ضريبة',
  FREE: 'مجانا',
  AMOUNT_PAYBLE: 'المبلغ المستحق',
  SELECT_PAY_METHOD: 'اختر طريقة الدفع',
  PAY_WITH_DEBIT: 'ادفع ببطاقة الخصم',
  PAY_WITH_CREDIT: 'دفع مع بطاقة الائتمان',
  CARD_ADD: 'إضافة بطاقة',
  NAME_ON_CARD: 'الاسم على البطاقة',
  ENTER_DATE: 'تاريخ انتهاء الصلاحية',
  CONTINUE: 'استمر',
  PAYMENT_OPT: 'خيارات الدفع لهذا الطلب:',
  PLACE_ORDER: 'مكان الامر',
  ITEM: 'العنصر',
  ITEM2: 'العنصر',
  PAYMENT: 'دفع',
  PAY_SUCCESS: 'الدفع الناجح',
  PAY_SUCCESS2: 'شكرا لك على الشراء!',
  ORDER_NO: 'رقم الطلب الخاص بك هو:',
  PAY_SUCCESS3: 'سنرسل لك رسالة بريد إلكتروني لتأكيد الطلب مع التفاصيل ومعلومات التتبع.',
  SHOW_RESULT: 'نتيجة العرض',
  MORE_THAN: 'أكثر من',
  NO_PRODUCTS: 'لا توجد منتجات : (',
  Select_Categories:'حدد الفئات',
  ENTER_NEW_PASS: 'أدخل كلمة مرور جديدة',
  OLD_PASS: 'كلمة المرور القديمة',
  ENTER_OLD_PASS: 'الرجاء إدخال كلمة المرور القديمة.',
  MY_ORDERS: 'طلباتي',
  UPCOMING: 'القادمة',
  COMPLETED: 'مكتمل',
  CANCELLED: 'ألغيت',
  NO_ORDERS: 'لا توجد طلبات حتى الآن!',
  ORDER_SOMETHNG: 'اطلب شيئا',
  ORDER_ID: 'رقم التعريف الخاص بالطلب',
  DATE:'تاريخ',
  New_Balance:'الرصيد الجديد',
  Apply_Store_Credit:'رصيد تخزين المبلغ',
  Apply_Store_Credit_Amount:'رصيد تخزين المبلغ',
  Action:'رقم التعريف الخاص بالطلب',
  DELIVERY_DATE: 'تاريخ الوصول المتوقع',
  TOTAL_AMT: 'المبلغ الإجمالي',
  NO_PRE_ORDERS: 'لا توجد طلبات سابقة!',
  NO_CANCEL_ORDER: 'لا توجد أوامر ملغاة!',
  PENDING: 'قيد الانتظار',
  PROCESSING: 'يعالج',
  OUT_FOR_DELIVERY: 'خارج للتوصيل',
  ARRIVING: 'قادمة',
  DELIVERED: 'تم التوصيل',
  ORDER_STATUS: 'حالة الطلب',
  WISH_LIST_EMPTY: 'قائمة رغباتك فارغة!',
  SEARCH_SELLERS: 'ابحث عن البائعين حسب اسم المتجر هنا ...',
  TOTAL_PRO: 'إجمالي المنتجات',
  SELLER_LIST: 'قائمة البائعين',
  PRO_LIST: 'قائمة المنتجات',
  VENDORS_REVIEWS: 'مراجعات البائعين',
  PRODUCT: 'منتج',
  REVIEW_ERR: 'آسف! أنت غير قادر على إعطاء رأي',
  AVG_RATE: 'متوسط ​​تقييم',
  POSITIVE_FB: '٪ ردود الفعل الإيجابية',
  WRITE_REVIEW: 'اكتب مراجعتك',
  AVG_PRICE_RATE: 'متوسط ​​تصنيف السعر',
  AVG_VALUE_RATE: 'متوسط ​​تقييم القيمة',
  AVG_QUALITY_RATE: 'متوسط ​​تقييم الجودة',
  CONTACT_US: 'اتصل بنا',
  CONTACT_US2: 'اتصل بنا',
  CONTACT_NOTE: 'قم بتدوين ملاحظة وسنقوم بالرد عليك في أسرع وقت ممكن.',
  ENTER_PHONE: 'أدخل رقم الهاتف',
  WHATS_ON_MIND: 'ما الذي يدور في ذهنك؟',
  ABU_DHABI: 'أبو ظبي ،',
  UAE: 'الإمارات العربية المتحدة (الإمارات العربية المتحدة)',
  SELECT_LAN: 'اختار اللغة',
  CUSTOMER: 'عميل',
  CUSTOMER_REVIEW: 'رأي العميل',
  OUT_OF_5: 'من 5',
  GLOBAL_RATINGS: 'التصنيفات العالمية',
  REVIEW_ON: 'مراجعة على',
  REFUND: 'استرداد',
  CREDIT_REFUND:'استرداد رصيد المتجر',
  STORE_CREDIT_BALANCE:'رصيد تخزين الائتمان',
  NO_SELLER: 'لم يتم العثور على بائع',
  DELETE_CONFIRM: 'هل أنت متأكد من حذف هذا العنصر',
  REGISTERED_MAIL: 'الرجاء إدخال معرف البريد المسجل',
  CHECK_MAIL: 'رجاء تفحص بريدك الإلكتروني',
  EMAIL_SENT: 'لقد أرسلنا لك البريد لإعادة تعيين كلمة المرور.',
  SESSION: 'انتهت الجلسة الرجاء تسجيل الدخول مرة أخرى',
  Are_you_sure_you_want_to_Exit:'هل أنت متأكد أنك تريد الخروج',
};


