export default {
  START_AS_A_TRADERS: 'Start as a Traders Platform',
  START_DESC: `Tomorrow's ecological life is free in real estate. It is not a gate or a pure truck.`,
  LANGUAGE_PAGE_P1: '',
  LANGUAGE_PAGE_P2: '',
  LANGUAGE_PAGE_P3: '',
  ENGLISH: 'ENGLISH',
  ARABIC: 'ARABIC',
  Delete_Account:"Delete Account",
  Delete_Your_Account:'Are you sure to delete your account?',
  OR: 'OR',
  SEARCH: "Search",
  SIGNNOW: "Sign Now",
  LOGIN: "LOGIN",
  SIGN_IN_AS_A_TRADERS: "Sign In as a Traders",
  ENTER_YOUR_EMAIL: "Reset Password",
  ENTER_YOUR_PHONE_NUMBER :"Enter your Mobile Number",
  EMAIL: "Email",
  Mobile_Number : 'Mobile Number',
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password?",
  DONT_HAVE_ACCOUNT_SIGNIN: "Don't have account?",
  GET_STARTED: "Get Started",
  LOADING: 'Loading...',
  FORGET_YOUR_PASSWORD: 'Forgot Your Password?',
  LOGIN_WITH_MOBILE_NUMBER:'LOGIN WITH OTP',
  ENTER_YOUR_ONE_TIME_OTP: 'Enter One Time Password',
  SUBMIT: 'SUBMIT',
  SEND_OTP: 'SEND OTP',
  SEND_EMAIL: 'SEND EMAIL',
  ENTER_OTP: "Enter OTP",
  VERIFY:"VERIFY OTP",
  GOOGLE: 'Google',
  FACEBOOK: 'Facebook',
  TRADER_BTN: 'TRADER',
  SIGNUP: 'SIGN UP',
  ENTER_NAME: 'Enter Name',
  BUSINESS_NAME: 'Business Name',
  ENTER_EMAIL_ID: "Enter Email",
  MOBILE_NUMBER: 'Mobile Number',
  CONFIRM_PASSWORD: "Confirm Password",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  ALREADY_HAVE_ACCOUNT_LOGIN: 'Already have account?',
  TOTAL: 'Total',
  PRODUCT_ARE_AVALIABLE: 'products are available',
  HI: 'Hi',
  HOME: 'Home',
  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  MESSAGE: 'Message',
  LOGOUT: 'Logout',
  UPDATE: 'UPDATE',
  ADD_PRODUCT: 'Add Products',
  TO_DO_LIST: 'To Do List',
  ACCOUNT: 'Account',
  PRODUCT_CATEGORY: 'Product Category',
  PRODUCT_SUB_CATEGORY: 'Product Sub Category',
  PRODUCT_TITLE: "Product Tttle",
  DESCRIPTIOn: 'Description',
  PRICE: 'Price',
  QUANTITY: 'Quality',
  MAX_ORDER: 'MAX Order',
  COLOR: 'Color',
  SIZE: 'Size',
  XL: 'XL',
  L: 'L',
  M: 'M',
  S: 'S',
  XS: 'XS',
  CAP_ADD_PRODUCT: 'ADD PRODUCT',
  SIGN_IN: 'Sign In',
  EMAIL_ERR: 'Please enter the email address.',
  LOGIN_1: 'Login',
  CANCEL: 'CANCEL',
  OK: 'OK',
  VALID_EMAIL: 'Please enter a valid email address.',
  ENTER_PASS: 'Please enter the password.',
  NEWPASSWORD:'New Password',
  ENTER_CONPASS: 'Please enter the confirm password.',
  ENTER_NEWPASS: 'Please enter the new password.',
  PASS_ERR: 'Password should have at least 8 characters long, one uppercase letter, one lowercase letter and contains at least one digit.',
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_SUCCESS2: 'your login is successful',
  LOGIN_FAIL: 'Login failed',
  LOGIN_FAIL2: 'Please try again later.',
  TREND_COLL: 'Trending Collection',
  MYORDER: 'My Order',
  MYCART: 'My Cart',
  MYWISH: 'My Wishlist',
  ALLTRAD: 'All Traders',
  PRODUCTS: 'Products',
  CUSTOMERSERV: 'Customer Service',
  FAQ: 'FAQ',
  PRIVACYPOL: 'Privacy Policy',
  ABOUTUS: 'About Us',
  AED: 'AED',
  REVIEWS: 'reviews',
  REVIEW: 'review',
  REVIEW2: 'Review *',
  ADDTOCART: 'Add To Cart',
  SUBMITREVIEW: 'Submit Review',
  ADDEDCART: 'Added to cart',
  CARTTOTAL: 'Cart Total',
  CONTISHOPPING: 'Continue Shopping',
  CHECKOUT: 'Checkout',
  PRODETAILS: 'Product Details',
  YOUAREREVIEWING: 'You are reviewing:',
  YOURRATING: 'Your Rating *',
  VALUE: 'Value',
  NICKNAME: 'Nickname *',
  SUMMARY: 'Summary *',
  SELECT_SUITABLE_SC: 'Please select suitable size and color',
  REVIEW_SUBMIT: 'Review Submitted',
  REVIEW_SUBMIT_FAILED: 'Review Submit Failed',
  LOGOUT_FROM_APP: 'Log out from app?',
  CHANGE_PASS_FAIL: 'Change Password failed',
  CHANGE_PASS_SUCCESS: 'Your password changed successfully.',
  Mobile_Number_Update:'Mobile Number Update',
  Old_MOBILE_NUMBER:'Old Mobile Number',
  New_MOBILE_NUMBER:'New Mobile Number',
  Get_Otp:'Get OTP',
  REGISTRATION: 'Registration',
  ENTER_THE_NAME: 'Please enter the name',
  ENTER_PHONE_NO: 'Please enter the phone number.',
  ENTER_10DIGIT_NO: 'Please enter correct UAE mobile number.',
  PASS_NOT_MATCH: 'Confirm password does not match to password.',
  ACCEPT_TC: 'Please accept our Terms & Conditions.',
  REG_SUCCESS: 'Registration successful',
  REG_SUCCESS2: 'You registered successfully',
  REG_ERR: 'Registration faild',
  PROFILE_UPDATED_SUCCESS: 'Profile successfully updated.',
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again.',
  NAME: 'Name',
  DATE_OF_BIRTH: 'Date of Birth',
  DATE_OF_META: 'Date of Meta Recurrence',
  DELETE_SUCCESS: 'Delete successfully',
  CART: 'Cart',
  PROCEED_TO_BUY: 'PROCEED TO BUY',
  ITEMS: 'ITEMS',
  ITEMS2: 'Items',
  CART_EMPTY: 'Your meta shopping cart looks empty!',
  START_SHOPPING: 'START META SHOPPING',
  QUANTITY2: 'Quantity',
  DELETE: 'Delete',
  SUBTOTAL: 'Subtotal',
  FILL_ALL_FIELDS: 'Please fill all fields',
  ADDRESS: 'Address',
  ADDRESS_ADD_SUCCESS: 'Shipping address added successfully.',
  ADDRESS_ADD_FAIL: 'Address failed',
  PINCODE_NOT_AVAILABLE: 'This pincode is not available',
  SHIPPING_ADD: 'Shipping Address',
  NO_ADD: 'No address found.',
  DELIVERY_TO_ADD: 'Delivery to this address',
  EDIT_ADD: 'Edit address',
  ADD_NEW_ADD: 'Add new address',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  HOUSE_NO: 'House No',
  STREET_NO: 'Street No',
  CITY: 'City',
  ZIPCODE: 'Zipcode',
  STATE: 'State',
  COUNTRY: 'Country',
  TELEPHONE: 'Telephone',
  DEFAULT_SHIP_ADD: 'Set default shipping address',
  DEFAULT_BILL_ADD: 'Set default billing address',
  ENTER_CARD_NO: 'Please enter the number on card',
  ENTER_CARD_NAME: 'Please enter name on card',
  ENTER_EXPIRY_DATE: 'Please enter expiry date',
  ENTER_CVV: 'Please enter cvv',
  PRICE_DET: 'PRICE DETAILS',
  DELIVERY_CHARGES: 'Delivery charges',
  TAX: 'Tax',
  FREE: 'FREE',
  AMOUNT_PAYBLE: 'Amount Payable',
  SELECT_PAY_METHOD: 'Select a payment method',
  PAY_WITH_DEBIT: 'Pay with Debit card',
  PAY_WITH_CREDIT: 'Pay with credit card',
  NAME_ON_CARD: 'Name on card',
  ENTER_DATE: 'Expiry Date',
  CONTINUE: 'Continue',
  PAYMENT_OPT: 'Payment options for this order :',
  PLACE_ORDER: 'Place order',
  ITEM: 'ITEM',
  ITEM2: 'Item',
  PAYMENT: 'Payment',
  PAY_SUCCESS: 'Payment Success',
  PAY_SUCCESS2: 'Thank you for your purchase!',
  ORDER_NO: 'Your order number is:',
  PAY_SUCCESS3: 'We will email you an order confirmation with details and tracking info.',
  SHOW_RESULT: 'Show Result',
  MORE_THAN: 'More than',
  NO_PRODUCTS: 'No products : (',
  Select_Categories:'Select Categories : (',
  ENTER_NEW_PASS: 'Enter New Password',
  OLD_PASS: 'Old Password',
  ENTER_OLD_PASS: 'Please enter old password.',
  MY_ORDERS: 'My Orders',
  UPCOMING: 'Upcoming',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  NO_ORDERS: 'No orders yet!',
  Apply_Store_Credit_Amount:'Enter Amount to Apply',
  ORDER_SOMETHNG: 'Order something',
  ORDER_ID: 'Order Id',
  Apply_Store_Credit:'Apply Store Credit',
  DELIVERY_DATE: 'Estimated Delivery Date',
  TOTAL_AMT: 'Total Amount',
  NO_PRE_ORDERS: 'No Previous orders!',
  NO_CANCEL_ORDER: 'No Cancelled orders!',
  PENDING: 'Pending',
  PROCESSING: 'Processing',
  OUT_FOR_DELIVERY: 'Out for delivery',
  ARRIVING: 'Arriving',
  DELIVERED: 'Delivered',
  ORDER_STATUS: 'Order status',
  WISH_LIST_EMPTY: 'Your wish list is empty!',
  SEARCH_SELLERS: 'Search sellers by shop name here...',
  TOTAL_PRO: 'TOTAL PRODUCTS',
  SELLER_LIST: 'Seller list',
  PRO_LIST: 'Products list',
  VENDORS_REVIEWS: 'Vendors Reviews',
  PRODUCT: 'Product',
  REVIEW_ERR: 'Sorry! You are not able to give review',
  AVG_RATE: 'Average Rating',
  POSITIVE_FB: '% positive feedback',
  WRITE_REVIEW: 'Write your review',
  AVG_PRICE_RATE: 'Average price rating',
  AVG_VALUE_RATE: 'Average Value rating',
  AVG_QUALITY_RATE: 'Average Quality rating',
  CONTACT_US: 'Contact Us',
  CONTACT_US2: 'CONTACT US',
  CONTACT_NOTE: `Jot us a note and we’ll get back to you as quickly as possible.`,
  ENTER_PHONE: 'Enter phone number',
  WHATS_ON_MIND: 'Whats on your mind?',
  ABU_DHABI: 'Abu Dhabi',
  UAE: 'United Arab Emirates (U.A.E)',
  SELECT_LAN: 'Select language',
  CUSTOMER: 'CUSTOMER',
  CUSTOMER_REVIEW: 'Customer Review',
  OUT_OF_5: 'out of 5',
  GLOBAL_RATINGS: 'Global ratings',
  REVIEW_ON: 'Review on',
  REFUND: 'Refund & Exchange Policy',
  CREDIT_REFUND:'Store Credit & Refunds',
  STORE_CREDIT_BALANCE:'Store Credit Balance',
  New_Balance:'New Balance',
  NO_SELLER: 'No Seller found',
  DATE:'Date',
  DELETE_CONFIRM: 'Are you sure to delete this item?',
  REGISTERED_MAIL: 'Please enter registered mail id',
  CHECK_MAIL: 'Please check your mail',
  EMAIL_SENT: 'We have sent you the mail for reset the password.',
  SESSION: 'Session expired please login again',
  Are_you_sure_you_want_to_Exit:'Are you sure you want to Exit?',
  Action:'Action',
};